version: '2'
services:
  mattermost-api-interface:
    build: ./build
  mattermost-preview:
    image: mattermost/mattermost-preview
    ports:
      - 8065:8065
  # gray-elasticsearch:
  #   image: "elasticsearch:2"
  #   command: "elasticsearch -Des.cluster.name='graylog'"
  # graylog:
  #   image: graylog2/server:2.1.1-1
  #   environment:
  #     GRAYLOG_PASSWORD_SECRET: somepasswordpepper
  #     GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  #     GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
  #   links:
  #     - gray-mongo:mongo
  #     - gray-elasticsearch:elasticsearch
  #   ports:
  #     - "9000:9000"
  #     - "5140:5140/udp"
