version: '2'
services:
  asterisk-carrier:
    build: ./carrier
    image: devops/asterisk-carrier
    environment:
      - ASTERISK_TESTBOX=172.16.200.1
    networks:
      app_net:
        ipv4_address: 172.16.200.10
  asterisk-testbox:
    build: ./testbox
    image: devops/asterisk-testbox
    environment:
      - ASTERISK_CARRIER=172.16.200.10
    network_mode: host
    # volumes:
    #   - /etc/asterisk:/etc/asterisk
    #   - /etc/letsencrypt:/etc/letsencrypt
    # ports:
    #   - 3478:3478/tcp
    #   - 3478:3478/udp
    #   - 5060:5060/tcp
    #   - 5060:5060/udp
    #   - 5061:5061/tcp
    #   - 5061:5061/udp
    #   - 8088:8088/tcp
    #   - 8089:8089/tcp
    #   - 10000-10099:10000-10099/udp
    #   - 19302:19302/tcp
    #   - 19302:19302/udp

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.200.0/24
        gateway: 172.16.200.1
